### ISSUE TITLE
[Home Page] Announcements Issues

### ISSUE THREAD

**Issue by daaray** [PyCon/pycon#107]
- [x] Reconcile Teaser/Content editing and rendering
- [x] Verify that (un)publish flag works as intended
- [x] Ensure blog post date is rendering correct information (publish date, most likely)

**Comment by brandon-rhodes** [comment]
I note that “Reconcile Teaser/Content editing and rendering” is still something of an issue, even for the 2016 site, so I am going to label this issue to bring it more attention.

**Comment by brandon-rhodes** [comment]
I have finally checked off the first item here thanks to fixing #580, so after two and a half years this issue can be closed!
