### ISSUE TITLE
Review if Conference Sections should have unique slugs

### ISSUE THREAD

**Issue by daaray** [PyCon/pycon#214]
The Review section throws an error if multiple Conference Sections exist with the same slug:

https://github.com/caktus/pycon/blob/develop/symposion/reviews/views.py#L89

**Comment by brandon-rhodes** [comment]
That field is a Django `models.SlugField` and it looks like Django now correctly enforces uniqueness on the slug — when I try creating a new Section with the same slug as an existing Section, I get the error message in the Django admin interface:

    Section with this Conference and Slug already exists

I am therefore closing this issue in the hopes that this will not recur!
