### ISSUE TITLE
server.py modifies django.util.log.DEFAULT_LOGGING

### ISSUE THREAD

**Issue by IanLewis** [PyCon/pycon#285]
pycon/settings/server.py imports DEFAULT_LOGGING and makes a copy of it but the copy is not a deep copy so the subsequent lines that call update() on the keys of the copy are actually modifying the values in the original DEFAULT_LOGGING dict.

DEFAULT_LOGGING is imported and loaded by a dictConfig() before the actual LOGGING dict is set up so this can cause issues if you later define formatters or other settings directly on the LOGGING dict in server.py.

**Comment by dpoirier** [comment]
I fixed this a few weeks ago along with some other things, but would not have known about the problem without this issue being opened; thank you!
