### ISSUE TITLE
Enhancement: Enable a talk reviewer an easy option to display talks up for review

### ISSUE THREAD

**Issue by willingc** [PyCon/pycon#342]
With the kitten changes for PyCon 2015, it would be helpful if reviewers could select all talks that are up for voting in a particular week of kitten easily.

**Comment by brandon-rhodes** [comment]
Since the Talks committee is using their own app this year, I think that we can temporarily close this issue for the 2016–2017 season? We can revisit this later if a future Talks committee decides to make another try at using the PyCon app again.
