### ISSUE TITLE
PC-specific fields in the proposal list UI

### ISSUE THREAD

**Issue by rdodev** [PyCon/pycon#365]
Currently the proposal list UI has several fields (thunderdom, overall status, etc) that are used by the PC in their approval workflow. Not all committees use those fields and are in fact the cause of much confusion. The most flexible approach would be to have per-user preferences and be able to customize the display of columns.

**Comment by brandon-rhodes** [comment]
As the “Thunderdome” column does seem, at least, to have disappeared from the proposal list grids, I am going to close this issue. If at any future point someone wants to open a more specific issue that targets the remaining fields that we do display, we can consider that more narrow proposal specifically.
