### ISSUE TITLE
Ability to have per-committee proposal voting rules

### ISSUE THREAD

**Issue by rdodev** [PyCon/pycon#366]
Currently anyone _can_ go straight to the voting page, see the votes and comments up to that point and cast a vote and echo opinions, in the best of cases. In a more problematic case, the reviewer either accidentally or on purpose sees voting before reading the proposal and biases that reviewer's review.

We should have the ability to set rules (locally to each committee, not globally) to avoid these type of scenarios. For instance:
 * not showing comments or votes until a reviewer has already voted.
 * making it impossible to jump to the voting or feedback areas directly unless that reviewer already has reviewed or voted on said proposal.

**Comment by brandon-rhodes** [comment]
As the Talks PC now uses its own app for voting, I suspect that we can safely remove per-committee voting rules from the roadmap for the main site for 2016, so I am closing this issue for now. We can revisit the topic if either of the two remaining committees (Tutorials and Posters) needs customization, or if the Talks committee at some future date wants to return to using the main PyCon site.
