### ISSUE TITLE
Email the PyCon sponsors list when new sponsorship applications come in

### ISSUE THREAD

**Issue by dianaclarke** [PyCon/pycon#367]
Right now, I check a few times a day for new PyCon sponsorship applications:

    https://us.pycon.org/2015/admin/sponsorship/sponsor/?o=5.1

It would help a lot if the app just emailed the PyCon sponsors mailing list with any new sponsorship applications.

The company name of the sponsor should be in the email subject.

The PyCon sponsors mailing list is:

    pycon-sponsors@python.org

**Comment by dpoirier** [comment]
This got implemented at some point; closing the issue.
