### ISSUE TITLE
Sponsor Workshops should be part of the program export

### ISSUE THREAD

**Issue by felixc** [PyCon/pycon#372]
Currently the program export functionality doesn't include Sponsor Workshops/Sponsor Tutorials. It would be great if they could be exported as well.

If it's not a trivial/quick fix, that's fine for this year; there are few enough of them that I can easily copy them to the mobile guide manually. Of course, if it *is* a quick fix, that would be fantastic :)

**Comment by rebecca-caktus** [comment]
You're in luck! It was a straightforward change, and has been deployed to production. Files for sponsor tutorials are at `program_export/presentations/csv/sponsor_tutorials.csv` and `program_export/presentations/rtf/sponsor_tutorials.rtf`.

Fixed in f07a1a3.

**Comment by dianaclarke** [comment]
Thanks @felixc & @rebecca-caktus!!

**Comment by felixc** [comment]
Thank you! It's all there and looks great.
