### ISSUE TITLE
When I try to send email to tutorial attendees, I receive CSRF verification fail - 403

### ISSUE THREAD

**Issue by jackiekazil** [PyCon/pycon#374]
Error:
```
Forbidden (403)
CSRF verification failed. Request aborted.
More information is available with DEBUG=True.
```

To recreate the error:
1. Login to the PyCon site. 
2. Click on the Dashboard to go here: http://us.pycon.org/2015/dashboard/
3. Click on Tutorial title as a tutorial instructor, that takes me here: http://us.pycon.org/2015/schedule/presentation/318/
4. Try to send email or leave class note. 
5. 403 returned.

**Comment by ceilous** [comment]
I just tried this with one participant in Python by Immersion and did not get an error.

**Comment by jackiekazil** [comment]
I just tried again and didn't have the issue. I am going to close this.
