### ISSUE TITLE
Mandatory sponsor data

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#379]
make it mandatory for sponsor to add company link, web description and web logo when applying for sponsorship.

**Comment by calebsmith** [comment]
I believe I've found where this is in the code but I'm not certain where the "web description" bit is, or if it needs to be added?

**Comment by calebsmith** [comment]
Also, I think sponsors choose to pay for a "logo benefit" so can we really require a logo or?

**Comment by briseling** [comment]
From Ewa: "The web description is the description of the sponsor company listed on the website. It is different from the "printed program description", which does not get listed on the website.

Everyone who sponsors PyCon is any way gets their logo on the website site: Keystone, Diamond, Platinum, Gold, Silver, Media, OSS, Patron, custom level."
