### ISSUE TITLE
Talk URL update endpoint (use Django Rest Framework)

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#389]

**Comment by dpoirier** [comment]
I think this text from a document Ben found is what this issue is talking about:

TALKS/SESSION CHAIRS
	•	Add the following fields to each talk slot:	
	⁃	Talk video URL
	⁃	Talk slides URL	
	⁃	Talk assets URL
	⁃	Those fields should exist in the /schedule/conference.json feed
	⁃	There should be an API which I can use to update those URLs
	⁃	it should be as simple as possible, since I'll call it from scripts
	⁃	I don't care what it looks like, so long as I can call it with 3 lines 
		of requests (ex, no oauth or anything complex)
	⁃	Those fields should be editable from the django admin
	⁃	If present and non-empty, they should be shown on the talk description page

**Comment by dpoirier** [comment]
Or maybe they apply to #386?

**Comment by dpoirier** [comment]
Fixed in #425.
