### ISSUE TITLE
Simple Session Staff API chair and runner changes

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#390]
Simple Session Staff API that renders chair and runner info for each schedule conference session

**Comment by dpoirier** [comment]
Some text that Ben found:

•	An API endpoint which will return the session chairs and runners. Whatever 
		is the absolute simplest to implement which I can 
                cross reference against the conference.json feed:

    GET /schedule/session-staff.json
    [
        {
            "conf_key": 123, // fk into conference.json
            "chair_name": "Jane Smith",
            "chair_email": "jane@smith.net",
            "runner_name": "John Doe",
            "runner_email": "john@doe.net",
        },
    ]

**Comment by wolever** [comment]
Oh, d'oh! Didn't see this one yesterday. Yes, this is exactly it.

The two things I'd add:

- Since it contains volunteer names and emails, it should only be available to staff / superusers.

- Use case: I have a script which generates a green-room schedule. This API endpoint will let me include the runner names and email addresses in that printout.

**Comment by dpoirier** [comment]
I'll make this API only available with a valid Pycon API key, like some of the other APIs.  Those should only be given out to staff.

**Comment by wolever** [comment]
Okay, perfect.

And to double check: it will be possible to use the Admin to generate API keys, or something similarly straight forward?

> On Aug 17, 2015, at 10:32 AM, Dan Poirier <notifications@github.com> wrote:
> 
> I'll make this API only available with a valid Pycon API key, like some of the other APIs. Those should only be given out to staff.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PyCon/pycon/issues/390#issuecomment-131841428>.
> 

--
phone: (416) 906-0403
pgp: B230230D

**Comment by dpoirier** [comment]
Yes, you can just use the Django admin to create API keys.

Though I've just been reviewing the code and use of the API key does require computing a timestamp and signature to include on the request, which might be heavier than you want to deal with.  (Example code: https://github.com/PyCon/pycon/blob/62646265357afe0a28690e9b06978628e9dde895/pycon/pycon_api/tests.py#L53)

What do you think?

**Comment by wolever** [comment]
A timestamp’d signature would be totally fine :) Just make sure there’s an example somewhere I can copy+paste from.

> On Aug 17, 2015, at 10:53 AM, Dan Poirier <notifications@github.com> wrote:
> 
> Yes, you can just use the Django admin to create API keys.
> 
> Though I've just been reviewing the code and use of the API key does require computing a timestamp and signature to include on the request, which might be heavier than you want to deal with. (Example code: https://github.com/PyCon/pycon/blob/62646265357afe0a28690e9b06978628e9dde895/pycon/pycon_api/tests.py#L53 <https://github.com/PyCon/pycon/blob/62646265357afe0a28690e9b06978628e9dde895/pycon/pycon_api/tests.py#L53>)
> 
> What do you think?
> 
> 

--
phone: (416) 906-0403
pgp: B230230D

**Comment by dpoirier** [comment]
Great. I'll be improving the API docs in #392 and will be sure to include some sample code.  Thanks!

**Comment by dpoirier** [comment]
Fixed in #484
