### ISSUE TITLE
"A problem occurred with this webpage so it was reloaded." on iOS

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#429]
![screen shot 2015-07-27 at 3 50 25 pm](https://cloud.githubusercontent.com/assets/8808771/8916287/81b05e0e-3478-11e5-9b38-643a52b0d537.png)
On Saucelabs, using iPhone 6/iOS 8.1 Safari, I repeatedly got a message that said, "A problem occurred with this webpage so it was reloaded."

**Comment by briseling** [comment]
Hayley if you are looking at a screen with last year's design on it the ticket is not yet ready for you. Hold on until @rayt86 deploys the new home page with the new design as that is what we'll need to have the resopnsive check done on.

**Comment by hatlas** [comment]
Previous version of site.
