### ISSUE TITLE
Not showing social auth login links

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#441]
E.g. at https://pycon-staging.global.ssl.fastly.net/2016/account/login/ there should be links to login using Google or Yahoo.

I think this is because the `{% block sidebar %}` in the `login.html` template, that has those links, isn't being displayed by any of the parent templates.

**Comment by hatlas** [comment]
Passed QA. Login links are displayed (and working):
![screen shot 2015-09-03 at 9 14 47 am](https://cloud.githubusercontent.com/assets/8808771/9659109/4ea1ae52-521c-11e5-8bc0-a25b7b688104.png)
