### ISSUE TITLE
"Past Pycons" slideshow stays highlighted when clicked

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#442]
Clicking the "past Pycons" slideshow causes it to stay highlighted (the blue border around it). This seems like it might not be intended behavior.
![screen shot 2015-07-30 at 3 21 53 pm](https://cloud.githubusercontent.com/assets/8808771/8992840/da1d1e3a-36ce-11e5-9f84-0a1d8cb656a3.png)
![screen shot 2015-07-30 at 3 21 47 pm](https://cloud.githubusercontent.com/assets/8808771/8992841/dbe03680-36ce-11e5-8e7d-918096537172.png)

**Comment by rayt86** [comment]
fixed and merged.
