### ISSUE TITLE
Occasional error messages on iOS

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#450]
On iOS 8.1, I occasionally get a message that says, "A problem occurred with this webpage so it was reloaded."
![screen shot 2015-08-03 at 8 47 46 am](https://cloud.githubusercontent.com/assets/8808771/9039874/5e25de88-39cc-11e5-9ef9-9f75a8df1a0e.png)

This only happens on iOS Simulator. I haven't been able to get it to happen on an actual device so far. Here are the messages that came up in the system log when it occurred on Saucelabs:
![screen shot 2015-08-03 at 11 17 08 am](https://cloud.githubusercontent.com/assets/8808771/9040647/827d2cf0-39d1-11e5-84eb-569b00548b24.png)
Here's the System Log messages that came up around when it occurred on the iOS Simulator on my computer:
```
Aug  3 11:29:24 172-20-0-177 com.apple.CoreSimulator.SimDevice.D014A524-A78F-4933-9E6C-68A85BF43C9B.launchd_sim[12073] (com.apple.WebKit.WebContent.80D6A141-73E0-4187-9414-560714FDCD0C[12119]): Service exited due to signal: Floating point exception: 8
Aug  3 11:29:25 172-20-0-177 com.apple.CoreSimulator.SimDevice.D014A524-A78F-4933-9E6C-68A85BF43C9B.launchd_sim[12073] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
Aug  3 11:29:25 172-20-0-177 assertiond[12088]: assertion failed: 14E46 12B411: assertiond + 11523 [3F572A0B-7E12-378D-AFEE-EA491BAF2C36]: 0x1
Aug  3 11:29:27 172-20-0-177.caktus.lan securityd[12237]:  SecTaskCopyAccessGroups No keychain access group specified whilst running in simulator, falling back to default set
Aug  3 11:29:40 172-20-0-177 assertiond[12088]: assertion failed: 14E46 12B411: assertiond + 11523 [3F572A0B-7E12-378D-AFEE-EA491BAF2C36]: 0x1
Aug  3 11:30:18 172-20-0-177 assertiond[12088]: assertion failed: 14E46 12B411: assertiond + 11523 [3F572A0B-7E12-378D-AFEE-EA491BAF2C36]: 0x1
```

**Comment by brandon-rhodes** [comment]
That error message looks like an internal memory error deep inside of the iOS stack. Unless it can either be linked to some specific behavior of the site HTML, CSS, or JS, or else can be replicated out on a real live iOS device and not just on a simulator, then I suspect that there is no path forward for diagnosing or resolving it. I am therefore going to provisionally close the issue. If more information should turn up, though, please feel free to re-open it!
