### ISSUE TITLE
Dropdown menu layers under dashboard panels

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#459]
![screen shot 2015-08-06 at 9 14 38 am](https://cloud.githubusercontent.com/assets/8808771/9112290/c7406b08-3c1b-11e5-9964-79e4690621ce.png)
The dropdown menus layer under the panels on the user dashboard.

**Comment by rayt86** [comment]
fixed in PR 480 but still needs to be merged.

**Comment by dpoirier** [comment]
#480 merged; @hatlas can you verify fix (should be on both staging and production so whichever is easier)

**Comment by hatlas** [comment]
Fix verified.
