### ISSUE TITLE
Nav bar shrinks, overlaps logo on sponsor app and registration pages

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#461]
https://staging-pycon.python.org/2016/sponsors/apply/
https://staging-pycon.python.org/2016/registration/register/

On these two pages, the nav bar appears smaller than usual and overlaps the logo.

![screen shot 2015-08-06 at 10 00 23 am](https://cloud.githubusercontent.com/assets/8808771/9113335/0704988a-3c22-11e5-9f2d-ca5e54ce3726.png)

**Comment by rayt86** [comment]
This has been fixed.
