### ISSUE TITLE
Registration banner on homepage

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#477]
The register now banner on the home page needs to be wider to accommodate more copy in the link.

**Comment by rayt86** [comment]
PR in for this

**Comment by dpoirier** [comment]
Fixed #478.

**Comment by hatlas** [comment]
Passed QA.

Appearance of banner, for reference:
![screen shot 2015-09-03 at 1 16 34 pm](https://cloud.githubusercontent.com/assets/8808771/9665399/0b182d4c-523e-11e5-9613-56e2b8721da7.png)
