### ISSUE TITLE
dropdown goes under sponsor carrousel 

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#479]
dropdown goes under the sponsor carrousel and needs to be fixed.

**Comment by rayt86** [comment]
PR in for this

**Comment by dpoirier** [comment]
Can you describe how to reproduce the problem?  I'm not seeing anything obvious.

**Comment by rayt86** [comment]
@dpoirier The comment I posted Friday didn't show up? That's odd. On pages with little page content, tike the log in page, long dropdowns, like the event dropdown, goes under the sponsor carrousel.

**Comment by dpoirier** [comment]
Fixed in #480.

**Comment by hatlas** [comment]
Passed QA; see also #520
