### ISSUE TITLE
Talks review table getting rendered below side menu

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#482]
See https://staging-pycon.python.org/2016/reviews/section/talks/

![talks](https://cloud.githubusercontent.com/assets/2788679/9276053/adcbf462-426f-11e5-9ee4-630eb4c7e128.png)

**Comment by hatlas** [comment]
Passed QA.
![screen shot 2015-09-03 at 9 20 42 am](https://cloud.githubusercontent.com/assets/8808771/9659199/15e64d1a-521d-11e5-8448-a24d26c74e01.png)
