### ISSUE TITLE
Financial Aid Review Page doesn't show applications

### ISSUE THREAD

**Issue by dchukhin** [PyCon/pycon#485]
from the dashboard I can click "Download applications" to download the applications, but clicking "Review applications takes me to a screen with no applications

![screenshot from 2015-08-17 15 39 58](https://cloud.githubusercontent.com/assets/6025153/9314450/0a6d66a4-44f7-11e5-8747-003c9990fec7.png)

**Comment by dchukhin** [comment]
There appears to be an extra ">" in the following function in pycon/templates/finaid/application_list.html:

        $(".tip").tooltip();
        $("table.table-finaid").dataTable({
          "sDom": "<'filter'<'sort'l><'search'f>r>t<'table-pagination'p>>",
          "sPaginationType": "bootstrap",
          "bStateSave": true
        });
in the line that begins with "sDom".
I suppose the line should be 

    "sDom": "<'filter'<'sort'l><'search'f>r>t<'table-pagination'p>"

**Comment by dchukhin** [comment]
Same thing appears to exist in pycon/templates/schedule/presentation_detail.html

**Comment by dchukhin** [comment]
fixed in #486

**Comment by hatlas** [comment]
Financial aid applications now correctly appear on finaid review page:
![screen shot 2015-09-02 at 2 05 48 pm](https://cloud.githubusercontent.com/assets/8808771/9639787/c52274e0-517b-11e5-9dff-3953467469c1.png)
