### ISSUE TITLE
New talk type for Education Summit

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#494]
"Ewa Jodlowska
The Edu Summit committee has asked if it is possible to use our site to collect their CFPS, reviews, etc - pretty much same process as talks just displayed elsewhere. The Edu Summit Schedule right now is put together here: https://us.pycon.org/2016/events/edusummit/schedule/. It is manually put together and not similar to our talk schedule. "

"Dan Poirier 
We'd do this by extending an existing talk type or base type."

See https://basecamp.com/1849796/projects/9507827/messages/46189632

**Comment by dpoirier** [comment]
Implemented in #521

**Comment by hatlas** [comment]
Seems to not show up on staging:
https://pycon-staging.global.ssl.fastly.net/2016/admin/proposals/proposalkind/
![screen shot 2015-09-10 at 2 03 45 pm](https://cloud.githubusercontent.com/assets/8808771/9796831/1f5ceeae-57c6-11e5-90d7-55d36c1e7cc6.png)

**Comment by hatlas** [comment]
Now it's all good:
![screen shot 2015-09-10 at 2 32 12 pm](https://cloud.githubusercontent.com/assets/8808771/9797373/c21ae3ce-57c8-11e5-8dc9-73d5b8c9cb0c.png)
