### ISSUE TITLE
Showing both English and French text fields

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#497]
https://basecamp.com/1849796/projects/9507827/messages/46916553

**Comment by dpoirier** [comment]
Fixed in #498.

**Comment by hatlas** [comment]
Passed QA; no more French

![screen shot 2015-09-02 at 3 14 44 pm](https://cloud.githubusercontent.com/assets/8808771/9641580/67cfb32a-5185-11e5-873e-24b4854f71cc.png)
