### ISSUE TITLE
Home page design updates

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#505]
Motto: 
* [x] The top and bottom rules should be 80% of the width of the text.
* [x] Need more space between the top and bottom rules and the motto text.
* [x] The font size should be larger, and the line height should be shorter.

City Skyline: 
* [x] Double check that the color of the city image and the tan background of the main content section are exactly the same color they are currently slightly different and that must be corrected.

**Comment by dpoirier** [comment]
Fixed #514

**Comment by hatlas** [comment]
Passed QA.

Old:
![screen shot 2015-09-03 at 2 23 13 pm](https://cloud.githubusercontent.com/assets/8808771/9667012/64641d62-5247-11e5-991e-4c6b0e9ce4b7.png)
![screen shot 2015-09-03 at 2 23 21 pm](https://cloud.githubusercontent.com/assets/8808771/9667017/6690932c-5247-11e5-918b-cab6194ce475.png)
New:
![screen shot 2015-09-03 at 2 23 27 pm](https://cloud.githubusercontent.com/assets/8808771/9667023/6a01fcee-5247-11e5-9c01-930cd2c516c5.png)
![screen shot 2015-09-03 at 2 23 33 pm](https://cloud.githubusercontent.com/assets/8808771/9667026/6c3972b2-5247-11e5-9b62-cc3b0262a5d0.png)
