### ISSUE TITLE
Indentation in first line of dropdown menus on homepage

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#510]
When viewed on the homepage, the first line of the dropdown menus in the nav bar are indented. They look like they should just be lined up with all the other menu items instead.
![screen shot 2015-08-27 at 12 04 25 pm](https://cloud.githubusercontent.com/assets/8808771/9525783/c862c550-4cb3-11e5-9e45-3009b8bee88e.png)

![screen shot 2015-08-27 at 11 57 31 am](https://cloud.githubusercontent.com/assets/8808771/9525763/b448dfd2-4cb3-11e5-9bfa-f28e543e5016.png)

**Comment by dpoirier** [comment]
@hatlas this has been fixed.

**Comment by hatlas** [comment]
Leaving open for now until I can access homepage.

**Comment by hatlas** [comment]
Passes QA:
![screen shot 2015-09-16 at 11 18 11 am](https://cloud.githubusercontent.com/assets/8808771/9909096/b2921382-5c64-11e5-8d33-cd36cbbe9581.png)
