### ISSUE TITLE
"About" menu appears in wrong spot

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#511]
The "about" menu on the nav bar appears on the far left when "About" is clicked, on desktop browsers.
![screen shot 2015-08-27 at 11 59 17 am](https://cloud.githubusercontent.com/assets/8808771/9525660/2f989390-4cb3-11e5-9ce1-9dfdabf53f2e.png)
All other menus appear directly under their associated menu option, as seen here with "Speaking":
![screen shot 2015-08-27 at 12 00 41 pm](https://cloud.githubusercontent.com/assets/8808771/9525689/54a25d74-4cb3-11e5-8116-bd9c8866c5b2.png)

**Comment by dpoirier** [comment]
@hatlas this was fixed at some point, you can verify on staging.

**Comment by hatlas** [comment]
Verified fixed:
![screen shot 2015-09-15 at 1 30 10 pm](https://cloud.githubusercontent.com/assets/8808771/9884477/eb257cfa-5bad-11e5-9be9-dc14a384017d.png)
