### ISSUE TITLE
Scrollbar on "past Pycons" slideshow

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#513]
The "a look at past Pycons" slideshow has a scrollbar at certain browser resolutions, such as 1024x768. It seems a bit odd and unnecessary, since the content could fit without having the scrollbar.
![screen shot 2015-08-27 at 3 26 51 pm](https://cloud.githubusercontent.com/assets/8808771/9530833/292266c2-4cd0-11e5-9735-1724885454cd.png)

**Comment by brandon-rhodes** [comment]
This was resolved as one of the checkbox items on #560.
