### ISSUE TITLE
Dropdown display underneath content

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#520]
We are assuming this is fixed now but we are wondering if this happens only if you are logged in or not. The issue is any navigation drop down appears below the content area.

**Comment by hatlas** [comment]
Fixed now, regardless of whether user is logged in:
![screen shot 2015-09-02 at 12 22 53 pm](https://cloud.githubusercontent.com/assets/8808771/9637178/5f592e78-516d-11e5-98dc-0bfe415b2de9.png)
![screen shot 2015-09-02 at 12 22 07 pm](https://cloud.githubusercontent.com/assets/8808771/9637186/61952066-516d-11e5-9c74-3532efa83b22.png)
