### ISSUE TITLE
"Pool of people whom are volunteering" > "Pool of people who are volunteering"

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#522]
![screen shot 2015-09-02 at 2 32 07 pm](https://cloud.githubusercontent.com/assets/8808771/9640425/7ff94124-517f-11e5-8c3a-b5efcfaf3302.png)
Grammatically, the "whom" in the definition of "volunteers" (appears on staff user dashboard) should be changed to "who".

**Comment by dpoirier** [comment]
Bleh.  I've fixed this in the fixture that would be used to create this team in a brand new site (ee1658a) and for the team on production.  Staging is currently down; I'll fix there when it's back.

**Comment by dpoirier** [comment]
I've now fixed this on staging. Ready for QA.

**Comment by hatlas** [comment]
Passed QA:
![screen shot 2015-09-03 at 9 08 55 am](https://cloud.githubusercontent.com/assets/8808771/9658994/7055039c-521b-11e5-9900-fdd4b71634ae.png)
