### ISSUE TITLE
QA for release 2016.7

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#523]
This is currently on staging.

Change list is at https://github.com/PyCon/pycon/blob/229917cffd32c056badbe439b8bf58750b223814/docs/changes.rst

Issues to QA:

* [x] #441
* [x] #469 
* [x] #477 
* [x] #482 
* [x] #504 
* [x] #505 
* [ ] #506 
* [x] #517

**Comment by hatlas** [comment]
Resolved; outstanding items under #506 have been moved to #526
