### ISSUE TITLE
add Caktus logo to footer and update favicon to new colors

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#525]
emulate the black and white logo from 2015

**Comment by hatlas** [comment]
Nice! Looks good on desktop and mobile:
![screen shot 2015-09-23 at 11 51 29 am](https://cloud.githubusercontent.com/assets/8808771/10050250/724949be-61e9-11e5-8f2e-74b8258b9e12.png)
![screenshot sep 23 2015 11-52-12 am](https://cloud.githubusercontent.com/assets/8808771/10050301/ad0e8eba-61e9-11e5-8c20-eaed36be32b8.png)

**Comment by hatlas** [comment]
And the favicon looks good too (checked in Chrome, FF, Safari, Android Chrome):
![screen shot 2015-09-23 at 11 57 50 am](https://cloud.githubusercontent.com/assets/8808771/10050439/54db3418-61ea-11e5-9174-c75fcd821f9a.png)
![screen shot 2015-09-23 at 11 57 45 am](https://cloud.githubusercontent.com/assets/8808771/10050441/5629fdcc-61ea-11e5-98f3-e52819bfdd73.png)
![screen shot 2015-09-23 at 11 59 31 am](https://cloud.githubusercontent.com/assets/8808771/10050480/97722c46-61ea-11e5-8187-9aec2509cd43.png)
![screen shot 2015-09-23 at 12 00 37 pm](https://cloud.githubusercontent.com/assets/8808771/10050513/bfd1bec2-61ea-11e5-98fc-7ad80452ed59.png)
