### ISSUE TITLE
Small fixes to navigation and CMS breadcrumbs

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#526]
* [x] Explore better solution for the account bar on desktop sized screens.
* [x] The active nav items' underline extends past the copy. It should end at the last letter of the nav item.
* [x] Active nav item adds a bottom border to all it's child LIs. Make sure it's only the main nav LI that gets the bottom border on hover/active.
* [x] On the CMS page, the hills image to the left of the breadcrumbs is a little shorter than the breadcrumb container. Fix me.

**Comment by brandon-rhodes** [comment]
Also, the active nav underline CSS also seems to introduce a separator line between each menu item in the pull-down beneath that nav item, which makes that one menu look different from the menus of all of the other nav items.

**Comment by rayt86** [comment]
I thought that had been resolved in an earlier PR, but I'll make sure it get resolved in this one.

**Comment by rayt86** [comment]
resolved in #537
