### ISSUE TITLE
Within user dashboard/404 page, teal area (forest) under nav bar moves down when nav bar options are hovered

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#527]
![screen shot 2015-09-03 at 1 10 03 pm](https://cloud.githubusercontent.com/assets/8808771/9665265/1cdebbc8-523d-11e5-9000-32e1c1502150.png)
![screen shot 2015-09-03 at 1 09 58 pm](https://cloud.githubusercontent.com/assets/8808771/9665267/1de76dee-523d-11e5-9345-0d5cd63e19c3.png)
When a logged-in user is viewing their dashboard or the "page not found" page, the space between the nav bar items and the "forest" below them increases when they are hovered over.

This doesn't happen on the "page not found" page for logged-out users.

**Comment by dpoirier** [comment]
@hatlas fixed on staging.

**Comment by hatlas** [comment]
QA confirmation: it's fixed on staging.
