### ISSUE TITLE
Remove basic auth from production

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#529]
Tentatively scheduled for Monday, 9/7 in the afternoon. Brandon will confirm.

**Comment by dpoirier** [comment]
Ben,

We'll need Ernest to take action when it's time for this to happen.

I'm guessing the timing on this isn't that critical, but if there's a time
when we absolutely need this to happen, we should coordinate with Ernest
ahead of time to figure out a plan for that.

Also, it's possible Ernest will be at the beach (or somewhere) on Monday,
so Tuesday might be better. Again, depending how critical this is, we
should plan today and communicate with Ernest.

Dmitriy,

On most Caktus projects, we'd disable basic auth by updating
conf/pillar/production.sls or conf/pillar/production/env.sls.

But this one is deployed by the PSF infrastructure team, not us, so what
we'll need to get done is to update pillar/base/pycon/prod.sls in the
https://github.com/python/psf-salt repo.

That repo is public, but we don't own it or have write permission on it, so
we can't create branches directly in it. Instead, we have a clone at
https://github.com/caktus/psf-salt.git. We create branches there and then
open pull requests against the upstream repo.

I've gone ahead and  made a branch with the change and pushed it to our
repo.  If you go to
https://github.com/python/psf-salt/compare/master...caktus:disable_pycon_basic_auth?expand=1,
hopefully you will see the change and have a button you can press (when the
time comes) to submit the pull request.  Please check it out and let me
know if you don't see that ready to go.

Often the infrastructure team sees a pull request and processes it quickly,
but it doesn't hurt to politely ping Ernest, EWDurbin on IRC, freenode, in
the #psf-infra channel.

Once they've merged the change, it should take effect within 10 minutes, or
immediately if Ernest triggers an immediate deploy.



*Dan Poirier*Developer

dpoirier@caktusgroup.com
www.caktusgroup.com

**Comment by dchukhin** [comment]
great, thanks for the explanation, @dpoirier !

**Comment by dpoirier** [comment]
11:32:48 <dpoirier
<https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/dpoirier>> EWDurbin:
by any chance will you be around on Monday?
11:32:57 <EWDurbin
<https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/EWDurbin>> i very
likely will!
11:33:47 <dpoirier
<https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/dpoirier>> we
might want to take the basic auth off the pycon site then, which would
require a small psf-salt pull request to be merged.
11:33:59 <EWDurbin
<https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/EWDurbin>> absolutely
can do!



*Dan Poirier*Developer

dpoirier@caktusgroup.com
www.caktusgroup.com

**Comment by ewdurbin** [comment]
Can confirm! I'll be around and available tomorrow. You can either mention me here (@EWDurbin) or hit me up in IRC freenode#python-infra.

**Comment by ewdurbin** [comment]
basic auth disabled https://github.com/python/psf-salt/pull/59.

**Comment by dpoirier** [comment]
Done.
