### ISSUE TITLE
Upgrade version of sitetree

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#534]
from Brandon:
Both Ewa and I have encountered the problem of temporarily hiding a sitetree item through the Admin interface, only to have it disappear and become impossible to bring back.

This appears to be a bug in sitetree that was recently fixed:
"https://github.com/idlesign/django-sitetree/pull/164

Could you upgrade the version of sitetree being used with the production site to the most recent trunk?"

**Comment by dchukhin** [comment]
The issue with disappearing seems to have been resolved in idlesign's django-sitetree repo (https://github.com/idlesign/django-sitetree) by pull request 169. Since our project uses our caktus/django-sitetree repo we should update our repo accordingly.

**Comment by dchukhin** [comment]
our repo has been updated

**Comment by dpoirier** [comment]
We should probably tweak our requirements to install a specific tag/commit/branch from our repo.

**Comment by dpoirier** [comment]
Fixed in our fork of django-sitetree.
