### ISSUE TITLE
QA 2016.8

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#535]
This is now on staging.  GitHub should link to the relevant issues, but let me know if anything is unclear.

* Fix missing image (#524, #530)
* Redirect from homepage to sponsor prospectus page (temporary) (#532)
* Send emails when presentations are saved in the admin (#496, #402)
* Add proposal type for education summit (#494, #521)

**Comment by hatlas** [comment]
"Redirect from homepage to sponsor prospectus page (temporary) (#532)" - passes QA
"Add proposal type for education summit (#494, #521)" - passes QA

"Fix missing image (#524, #530)" and "Send emails when presentations are saved in the admin (#496, #402)" still have some issues.

**Comment by dpoirier** [comment]
#524, #530 should be fixed by f3b4950 now on Staging.

**Comment by hatlas** [comment]
#496 is working; emails just weren't getting sent to pycon@caktusgroup.com (see https://github.com/PyCon/pycon/issues/402#issuecomment-139369872).

#524, #530 now pass QA
