### ISSUE TITLE
Image not found error

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#536]
An image not found error appears in the console while viewing the site:
>GET https://pycon-staging.global.ssl.fastly.net/2016/site_media/static/img/pycon-2016.png 404 (Not Found)

**Comment by dpoirier** [comment]
@hatlas can you use the official URL, https://staging-pycon.python.org/2016/, and verify this doesn't occur there?  That fastly.net URL was just temporary, I think (hope).

**Comment by hatlas** [comment]
Verified that this issue isn't present on official URL. therefore closing.
