### ISSUE TITLE
QA 2016.10

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#541]
Can we QA 2016.10, now on staging?

Contents include:

* Bug fix for Education Summit Proposals (#539, #540)
* Implement changes for some financial aid feedback (#508):

- [x] Python Experience Level: Should be a dropdown.
- [x] Sorting only sorts the names on the current page in review financial aid appellations page, not all.
- [x] Sorting doesn't sort correctly (we tried sorting date by see screenshot. Date field is being sorted lexicographically) (even when sorting just the names on the current page.)
- [x] "Grant letter sent" should have a drop-down Yes/No menu
- [x] "Cash check" should be called payment type
- [x] Travel Cash Check should go away.

* Changes to page nav/header and CMS styling (#537)

- [x] Fix navbar overlapping account links
- [x] Change account bar background and nav bar link padding
- [x] Fix navigation and breadcrumb issues

**Comment by hatlas** [comment]
I've QA'd all items. All items pass, except "The active nav items' underline extends past the copy. It should end at the last letter of the nav item." which I'm assuming is included under " Fix navigation and breadcrumb issues"
https://github.com/PyCon/pycon/pull/537#issuecomment-140865157

**Comment by brandon-rhodes** [comment]
I am closing this issue now, as all of its individual bullet points are checked off. Thanks for the work on it, everyone!
