### ISSUE TITLE
Edusummit proposals do not appear on edusummit review page

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#544]
I created a few test PyCon 2016 Education Summits as a normal user, then attempted to review them as an admin user, but they didn't show up on the review page (ie., https://staging-pycon.python.org/2016/reviews/section/edusummit/).

**Comment by dpoirier** [comment]
@hatlas I've deployed the fix for this to staging; please check it out :-)

**Comment by hatlas** [comment]
This issue is now fixed:
![screen shot 2015-09-17 at 10 49 53 am](https://cloud.githubusercontent.com/assets/8808771/9936580/af528640-5d2a-11e5-9981-49a1a3d40842.png)
