### ISSUE TITLE
Changing status of Pycon 2016 Education Summits causes an error.

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#547]
Edusummits are now showing up properly on Edusummit page (see #544), but changing their status (ie., "not Yet reviewed", "In Kittendome", etc.) on review page (https://staging-pycon.python.org/2016/reviews/section/edusummit/) leads to the following error:

>Oops, we've had a problem on the server. The web team have been informed and will be looking into it but if you have any questions, don't hesitate to email:

This only occurs with edusummits, not other types of proposal.

**Comment by dpoirier** [comment]
@hatlas The fix for this is deployed to staging for QA.

**Comment by hatlas** [comment]
Passes QA; here's a couple of edusummit proposals with successfully changed statuses.
![screen shot 2015-09-18 at 11 03 05 am](https://cloud.githubusercontent.com/assets/8808771/9962659/e1c8522e-5df4-11e5-8f93-be30e738bb02.png)
