### ISSUE TITLE
Submitting reviews for proposals intermittently causes error

### ISSUE THREAD

**Issue by hatlas** [PyCon/pycon#551]
If a staff user goes in and submits a review for a proposal (for instance, on this page: https://staging-pycon.python.org/2016/reviews/review/1555/#proposal-reviews), they get an error which reads:
>Oops, we've had a problem on the server. The web team have been informed and will be looking into it but if you have any questions, don't hesitate to email:

This doesn't always happen, but sometimes does. Maybe half of the time?

**Comment by dpoirier** [comment]
Fix is on staging for Q/A.

**Comment by hatlas** [comment]
The issue is still happening on staging. Here's one of the internal server error messages I got emailed:

Internal Server Error: /2016/reviews/review/1546/
Traceback (most recent call last):
 File "/srv/pycon/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/srv/pycon/pycon/symposion/reviews/views.py", line 295, in review_detail
   review.proposal = proposal
 File "/srv/pycon/pycon/symposion/reviews/models.py", line 122, in save
   ProposalResult.objects.get_or_create(proposal=self.proposal)
 File "/srv/pycon/pycon/symposion/reviews/models.py", line 281, in update_vote
   self.comment_count = models.F("comment_count") - 1
 File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 563, in update
   rows = query.get_compiler(self.db).execute_sql(CURSOR)
 File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
   cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
 File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
   sql, params = self.as_sql()
 File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1028, in as_sql
   (field.__class__.__name__, val.__class__.__name__))
TypeError: Database is trying to update a relational field of type DecimalField with a value of type ProposalScoreExpression. Make sure you are setting the correct relations

Request repr(): 
<WSGIRequest
path:/2016/reviews/review/1546/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'vote': [u'+1'], u'comment': [u'text'], u'csrfmiddlewaretoken': [u'gMGVlhkfBmWhdbmDs1rP774YoH5xU935'], u'vote_submit': [u'Submit Review']}>,
COOKIES:{'__utma': '32101439.1919584.1440091547.1441306222.1442335475.4',
'__utmc': '32101439',
'__utmz': '32101439.1440091547.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)',
'csrftoken': 'gMGVlhkfBmWhdbmDs1rP774YoH5xU935',
'sessionid': 'c8bjuoda81lnc5pnkebe4almky6pdtfx'},
META:{'CONTENT_LENGTH': '101',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
u'CSRF_COOKIE': u'gMGVlhkfBmWhdbmDs1rP774YoH5xU935',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
'HTTP_AUTHORIZATION': 'Basic cHljb246cG9ydGxhbmQyMDE2',
'HTTP_CACHE_CONTROL': 'max-age=0',
'HTTP_CONNECTION': 'close',
'HTTP_COOKIE': '__utma=32101439.1919584.1440091547.1441306222.1442335475.4; __utmc=32101439; __utmz=32101439.1440091547.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); sessionid=c8bjuoda81lnc5pnkebe4almky6pdtfx; csrftoken=gMGVlhkfBmWhdbmDs1rP774YoH5xU935',
'HTTP_HOST': 'staging-pycon.python.org',
'HTTP_ORIGIN': 'https://staging-pycon.python.org',
'HTTP_REFERER': 'https://staging-pycon.python.org/2016/reviews/review/1546/',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/2016/reviews/review/1546/',
'QUERY_STRING': '',
'RAW_URI': '/2016/reviews/review/1546/',
'REMOTE_ADDR': '127.0.0.1',
'REMOTE_PORT': '57403',
'REQUEST_METHOD': 'POST',
'SCRIPT_NAME': u'',
'SERVER_NAME': '127.0.0.1',
'SERVER_PORT': '8000',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SOFTWARE': 'gunicorn/19.3.0',
'gunicorn.socket': <socket._socketobject object at 0x7fe2f57b2f30>,
'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fe2f5330590>,
'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
'wsgi.input': <gunicorn.http.body.Body object at 0x7fe2f54c6bd0>,
'wsgi.multiprocess': True,
'wsgi.multithread': False,
'wsgi.run_once': False,
'wsgi.url_scheme': 'https',
'wsgi.version': (1, 0)}>

**Comment by dpoirier** [comment]
Weird - the mentioned type "ProposalScoreExpression" isn't even in the updated code, and I verified that's the code on the staging server.  Maybe the server process didn't restart for some reason?  I just force restarted it; can you try again?

**Comment by hatlas** [comment]
Can no longer reproduce. Looks fixed now!
