### ISSUE TITLE
Final front-end tweaks

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#558]
*[x] When I click on a nav heading, its underline becomes twice as thick and the whole site content drops by one or two pixels, then when I click again to close the nav menu the whole site moves up again.

*[ ] Final stray `text-transform: uppercase;` has remained in the CSS that the Venue pages are for some reason susceptible to when the other pages are not, as here:
https://us.pycon.org/2016/venue/weather/

*[ ] The sponsors page lacks breadcrumbs, and I think it would help keep users oriented if it had them:
https://us.pycon.org/2016/sponsors/

**Comment by dpoirier** [comment]
Fixed by #559.
