### ISSUE TITLE
Nav menu shifting

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#568]
Even after pressing Shift-Reload to try to make sure I have the most up to date stylesheets, but I still see the page shifting by maybe 2 pixels when I select a menu. For example, visit https://us.pycon.org/2016/ full-screen and click any menu name. Do you see the rest of the page shift downward as the nav menu comes up?

**Comment by chefscott** [comment]
@briseling If this is what you're referring to, it's not a bug but a feature:

![ezgif-2283333170](https://github-cloud.s3.amazonaws.com/assets%2F1245775%2F10957857%2F7e985bd8-8336-11e5-9b76-90fc6a2c2961.gif)

**Comment by dpoirier** [comment]
Is this about the menu moving down slightly after initially opening, as if animated?  Or is it about the rest of the page shifting anytime a menu is opened?
