### ISSUE TITLE
Responsive bug - Announcements overlap

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#569]
When the page narrows to less-than-full-screen, the "Announcements" overlap with the sponsor logos, as shown in the attached image.

And, though the Announcements section correctly shows the “teaser” paragraph that I entered for the first blog post, there is no “Read more” link that would take them to the full post at at https://us.pycon.org/2016/blog/2015/09/23/launch-day/ where the site hosts its blog.

**Comment by dpoirier** [comment]
Fixed by #578.
