### ISSUE TITLE
Sponsor pagination buttons not working on CMS pages

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#576]
From Ewa: 
on the sponsor logo "scrolls" at the bottom of each CMS page, the three buttons at the bottom of the scroll that are supposed to take you to the next set of sponsor logos, does not work.  That seems to be the case on the CMS pages. 

According to the screen shot they take you to the top of the same page, not the next page.

**Comment by dpoirier** [comment]
Fixed by #577.
