### ISSUE TITLE
Fix "<h2>" tags appearing on blog posts

### ISSUE THREAD

**Issue by brandon-rhodes** [PyCon/pycon#580]
Blog posts on the site are split in the database into a "Teaser" and "Content". While the Teaser displays fine, the Content is displayed incorrectly, with literal `<h2>` strings where titles should be. An example:

https://us.pycon.org/2016/blog/2015/10/29/registration-and-financial-aid-now-open/

This should be fixed so that the Content also displays with correct formatting.

**Comment by chefscott** [comment]
I cannot figure this one out... when I test it I get the same result as in header tags show up as literal strings but other tags like `<b>` or `<i>` correctly bold or italicize the text, it doesn't matter whether it's in the "Teaser" section or the "Content" section. I also fiddled with the Django "| safe" filter but that didn't do anything.
