### ISSUE TITLE
Remove "Sessions preference" from speaker/edit/

### ISSUE THREAD

**Issue by brandon-rhodes** [PyCon/pycon#581]
The Program Committee has this year decreed One Talk Per Person, so we should remove the "One" and "Two" options shown beneath the words "Sessions preference" in the speaker profile edit form, and instead just have a hidden field that gives the value "One". Maybe this should be configurable, since other conferences might use the side code and still want the option?

**Comment by chefscott** [comment]
Submitted a pull request: https://github.com/PyCon/pycon/pull/582.

**Comment by brandon-rhodes** [comment]
@chefscott — What if, instead of tackling this as a change at the level of the tests and database, we instead just hid the field and automatically set it to "1"? I think that a change to the form, while leaving the underlying schema intact and fully tested, would be easier for us to land without closing off the chance of using this feature again in the future, maybe?

**Comment by chefscott** [comment]
That's what I did before but  @ewdurbin suggested the migration -- let me know what's best.

**Comment by brandon-rhodes** [comment]
Happily, I fixed this a few months ago in 1c2faefd2e6f5e4ab0bdfbc7649247176b539d77!
