### ISSUE TITLE
Navigation underline bumps page down 2px

### ISSUE THREAD

**Issue by brandon-rhodes** [PyCon/pycon#590]
When I click on any of the top-level navigation bar items that are not the currently highlighted (and thus already underlined) item, the rest of the page bumps down two pixels, which I find a bit distracting. The CSS should be improved so that the rest of the page does not respond when I open one of the pull-down navigation menus.

**Comment by chefscott** [comment]
Is this the same thing as this issue: https://github.com/PyCon/pycon/issues/568

If not, please include a video or screenshot of some sort cause I'm not sure I am able to reproduce the same thing, at least on a Macbook running Chrome.

**Comment by brandon-rhodes** [comment]
Yes! It is precisely that issue. I am not sure why the earlier developer considered it a feature for an action up at the top of the page to make the whole rest of the page move up and down, but I would love if the lower part of the page stayed stationary during the operation.

**Comment by brandon-rhodes** [comment]
I am closing this issue as the 2016 site is now mothballed, so this will never be fixed — but as it only seemed to happen when I was logged on, and since no one will ever again be logged on to the now-static 2016 site, maybe it is actually not a problem any more for real!
