### ISSUE TITLE
Doubled name - Guillermo Pérez, Guillermo Pérez ?

### ISSUE THREAD

**Issue by kwadrat** [PyCon/pycon#594]
Talks schedule:
https://us.pycon.org/2016/schedule/talks/
May 30, 2016
Session E
10:50AM
For the talk "Python as a configuration language" there are two authors:Guillermo Pérez, Guillermo Pérez.
Is this single author? Or two different persons of the same name?

On his speaker profile:
https://us.pycon.org/2016/speaker/profile/1870/
The speaker gives 2 identical talks in the same time, in the same place.

**Comment by brandon-rhodes** [comment]
Thank you for pointing this out! His name got attached to the talk both as the speaker, and also as an "additional speaker", which resulted in his being listed twice. I have removed the "additional speaker" record, and now he is only showing up once.
