### ISSUE TITLE
"Copy" and "CSV" buttons not working

### ISSUE THREAD

**Issue by rdodev** [PyCon/pycon#608]
As per conversation with @brandon-rhodes there's an issue in the tutorial review section control that's causing those two buttons mentioned in the title to not behave as expected.

As a sanity check, same page and controls were tested in FF and MS Edge browsers. Those two exhibited the same issue.

![pycon-csv](https://cloud.githubusercontent.com/assets/1234335/21728188/efd761e4-d412-11e6-8989-73fa52e8e6c9.PNG)

I did some preliminary debugging with Chrome dev tools to figure out what was going on because for some reason the button "Print" button which is a sibling in the same control group works as intended. The conclusion is that for reasons still unknown data table events are not being bound to the former two while they are being bound to the latter.

Programmatically we can see this is the case as follows:

![pycon-events](https://cloud.githubusercontent.com/assets/1234335/21728183/e0e48860-d412-11e6-8bd1-76338a9e37c6.PNG)

Browsers tested:
* Chrome 55.0.2883.87
* MS Edge 39.14986.1000.0
* FF 45.6.0

**Comment by brandon-rhodes** [comment]
The library in use was very old, so I have attempted to deploy 1ad720a70b8a728f421f1ccc7334b5bfffa66502 to see if it fixes things. Let me know how the result looks from your end!
