### ISSUE TITLE
Receipt submit page does not work on Safari

### ISSUE THREAD

**Issue by karan** [PyCon/pycon#630]
Fin aid receipt submission page did not work on Safari last year.

**Comment by whit537** [comment]
Wfm under both Chrome 61 and Safari 11. I suggest closing pending better repro steps.

![screen shot 2017-10-16 at 12 09 25 pm](https://user-images.githubusercontent.com/134455/31622634-f5235bc6-b26a-11e7-881f-193f69e194e4.png)

**Comment by karan** [comment]
If this happens again, I'll get the specific browser, OS versions to help repro. Closing for now.
