### ISSUE TITLE
Reviews aren't displaying as rendered markdown

### ISSUE THREAD

**Issue by jesstess** [PyCon/pycon#636]
Reviews preview as expected -- rendered markdown with e.g. bullets, newlines.

Once submitted, they are rendered without the expected formatting, with all of the newlines removed.

**Comment by ewdurbin** [comment]
@jesstess sorry I missed this, for some reason I unwatched this repo 😢 

working on this now.

**Comment by ewdurbin** [comment]
Fixed, thanks for reporting @jesstess
