### ISSUE TITLE
Talk proposal description is not showing any links

### ISSUE THREAD

**Issue by kushaldas** [PyCon/pycon#640]
If I add any link using Markdown format, it shows up nicely on the preview in the *edit* section of a talk proposal. But, after I have submitted the talk, I can not see any URL link to click on the description or other parts in the talk proposal. 

I can see see them again if I try to edit the talk.

**Comment by ewdurbin** [comment]
This was an error that was fixed just this morning! We ended up with competing Markdown renderers :-x
