### ISSUE TITLE
Wrong Registration link on 5k page

### ISSUE THREAD

**Issue by SimiCode** [PyCon/pycon#678]
The link at https://us.pycon.org/2019/5k/: "Registration: Click Here!" goes to https://us.pycon.org/2018/registration/register/ instead of https://us.pycon.org/2019/registration/register/. 

I wanted to correct it but I can't seem to find the website content even when I try dog tricks like searching the repo. 
Please provide a link to the document containing this page for a reference.

**Comment by ewdurbin** [comment]
This was resolved, sorry for the confusion. It is a CMS page.
