### ISSUE TITLE
Microsoft PyCon 2020 Contract Addendum

### ISSUE THREAD

**Issue by bwaliszewski** [PyCon/pycon#692]
Can you take a look at the addendum Microsoft sent (ContractPro via DocuSign) and see if it's ok to sign.

I forwarded the email to you. Subject Line: esignature Request for Agreement : 3582761 - [Addendum] 98973136 PYTHON SOFTWARE FOUNDATION - Addendum

**Comment by ewdurbin** [comment]
this is probably better suited to https://github.com/python/psf
